### ISSUE TITLE
[Feature] THORChain Swap

### ISSUE THREAD

**Issue by johnnyluo** [voltix-vault/voltix-ios#162]
## Roadmap
- [x] SwapDetails screen
- [x] SwapVerify screen
- [x] Pairing flow
- [x] Swap transaction payload factory + relaying
- [x] More error handling and validations
- [x] Swap from/to amounts
- [x] Keyboard navigations
- [x] Streamswap support

#### Tested
- [x] BSC -> THOR
- [x] LTC -> BNB
- [x] USDT -> LTC
- [x] BNB -> LTC

**Comment by johnnyluo** [comment]
Also @flypaper0 could you please also add streamswap support to the list

**Comment by flypaper0** [comment]
Tasks from list completed
